# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fad8d399a5214da6aafd97aa01c1e7bdd570a4c59935849f45b333cb53823b56983a57616d215289e84572fc2f36e8984989e68d5ecec38538dfda16d788cc3

test:
  secret_key_base: a62558c95d488612a02201aed2eefac59e21a81242616c0727eaa07460616ede2475498336c1716caa4c84d749759bf200d561d44b82ad45ca8338a92fa709e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
